site: Afief Afian Weblog
url: https://afiefafian.github.io
title: Afief Afian Weblog
description: Simple and minimalistic jekyll blogging theme.
twitter:
  username: afifafian_
  card: summary
  creator: afifafian_
author:
  twitter: afifafian_
  name: Afief Afian
  avatar:
  email: afiefafian95@gmail.com
  url: https://afiefafian.github.io
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"